image: registry.geektr.co/t/yumemi:builder

stages:
  - build

before_script:
  - eval `yumemi docker-ci login`

docker-image:
  stage: build
  script:
    - yumemi docker-ci build
  only:
    changes:
      - "Dockerfile"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"
      - "src"
      - "bin"
